name: lispinto_chat
description: "A Flutter client for lisp-chat."
publish_to: 'none'

version: 2026.02.2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  gap: ^3.0.1
  package_info_plus: ^9.0.0
  prototype_constrained_box: ^2.0.3+1
  shared_preferences: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.6.3
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
